# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
